# Generated by Django 6.0.6 on 2026-06-20 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Titre du service')),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('icon_class', models.CharField(default='bx bx-code-alt', max_length=80, verbose_name='Classe icône Boxicons')),
                ('short_description', models.CharField(max_length=250, verbose_name='Description courte')),
                ('description', models.TextField(verbose_name='Description détaillée')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='services/covers/', verbose_name='Image de couverture')),
                ('color_accent', models.CharField(default='#2B7FD4', max_length=7, verbose_name='Couleur accent (hex)')),
                ('featured', models.BooleanField(default=False, verbose_name='Mis en avant')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('meta_description', models.TextField(blank=True, max_length=300, verbose_name='Méta description')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ServiceFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(default='bx bx-check', max_length=80, verbose_name='Icône')),
                ('title', models.CharField(max_length=150, verbose_name='Fonctionnalité')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('order', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='services.service')),
            ],
            options={
                'verbose_name': 'Fonctionnalité',
                'verbose_name_plural': 'Fonctionnalités',
                'ordering': ['order'],
            },
        ),
    ]
