# Generated by Django 6.0.6 on 2026-06-20 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('company', models.CharField(blank=True, max_length=150, verbose_name='Entreprise')),
                ('subject', models.CharField(choices=[('web', 'Développement web'), ('marketing', 'Marketing digital'), ('communication', 'Communication'), ('digital', 'Services numériques'), ('partnership', 'Partenariat'), ('other', 'Autre')], default='other', max_length=30, verbose_name='Sujet')),
                ('message', models.TextField(verbose_name='Message')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('replied_at', models.DateTimeField(blank=True, null=True, verbose_name='Répondu le')),
                ('ip_address', models.GenericIPAddressField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Reçu le')),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages de contact',
                'ordering': ['-created_at'],
            },
        ),
    ]
