# Generated by Django 6.0.6 on 2026-06-20 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, verbose_name='Question')),
                ('answer', models.TextField(verbose_name='Réponse')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Catégorie')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nom du partenaire')),
                ('logo', models.ImageField(upload_to='core/partners/', verbose_name='Logo')),
                ('website_url', models.URLField(blank=True, verbose_name='Site web')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Partenaire',
                'verbose_name_plural': 'Partenaires',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default="DAST NEWGEN'SPARK", max_length=100, verbose_name='Nom du site')),
                ('tagline', models.CharField(blank=True, max_length=200, verbose_name='Slogan principal')),
                ('tagline_sub', models.CharField(blank=True, max_length=300, verbose_name='Sous-slogan')),
                ('about_short', models.TextField(blank=True, verbose_name='Description courte')),
                ('about_long', models.TextField(blank=True, verbose_name='Description complète')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='core/logo/', verbose_name='Logo principal')),
                ('logo_white', models.ImageField(blank=True, null=True, upload_to='core/logo/', verbose_name='Logo blanc (footer)')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='core/favicon/', verbose_name='Favicon')),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='core/og/', verbose_name='Image Open Graph')),
                ('email_main', models.EmailField(blank=True, default='dastnewgenspark@gmail.com', max_length=254, verbose_name='Email principal')),
                ('email_secondary', models.EmailField(blank=True, max_length=254, verbose_name='Email secondaire')),
                ('phone_main', models.CharField(blank=True, default='+225 0173176410', max_length=30, verbose_name='Téléphone principal')),
                ('phone_secondary', models.CharField(blank=True, max_length=30, verbose_name='Téléphone secondaire')),
                ('whatsapp', models.CharField(blank=True, max_length=30, verbose_name='Numéro WhatsApp')),
                ('address', models.TextField(blank=True, verbose_name='Adresse physique')),
                ('google_maps_url', models.URLField(blank=True, verbose_name='Lien Google Maps')),
                ('google_maps_embed', models.TextField(blank=True, verbose_name="Code d'intégration Google Maps")),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('tiktok_url', models.URLField(blank=True, verbose_name='TikTok')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter / X')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub')),
                ('meta_description', models.TextField(blank=True, max_length=300, verbose_name='Méta description')),
                ('meta_keywords', models.TextField(blank=True, verbose_name='Mots-clés SEO')),
                ('google_analytics_id', models.CharField(blank=True, max_length=50, verbose_name='ID Google Analytics')),
                ('google_tag_manager_id', models.CharField(blank=True, max_length=50, verbose_name='ID Google Tag Manager')),
                ('stat_projects', models.PositiveIntegerField(default=0, verbose_name='Projets réalisés')),
                ('stat_clients', models.PositiveIntegerField(default=0, verbose_name='Clients satisfaits')),
                ('stat_years', models.PositiveIntegerField(default=0, verbose_name="Années d'expérience")),
                ('stat_team', models.PositiveIntegerField(default=0, verbose_name="Membres de l'équipe")),
            ],
            options={
                'verbose_name': 'Paramètres du site',
                'verbose_name_plural': 'Paramètres du site',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=150, verbose_name='Nom du client')),
                ('client_role', models.CharField(blank=True, max_length=150, verbose_name='Poste / Entreprise')),
                ('client_photo', models.ImageField(blank=True, null=True, upload_to='core/testimonials/', verbose_name='Photo')),
                ('content', models.TextField(verbose_name='Témoignage')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5, verbose_name='Note')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Témoignage',
                'verbose_name_plural': 'Témoignages',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
