# Generated by Django 6.0.6 on 2026-06-20 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Titre principal')),
                ('subtitle', models.CharField(blank=True, max_length=250, verbose_name='Sous-titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('cta_primary_text', models.CharField(default='Découvrir nos services', max_length=60, verbose_name='Bouton principal')),
                ('cta_primary_url', models.CharField(default='/services/', max_length=200, verbose_name='Lien bouton principal')),
                ('cta_secondary_text', models.CharField(blank=True, max_length=60, verbose_name='Bouton secondaire')),
                ('cta_secondary_url', models.CharField(blank=True, max_length=200, verbose_name='Lien bouton secondaire')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='home/hero/', verbose_name='Image de fond')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Slide hero',
                'verbose_name_plural': 'Slides hero',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ValueProposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(default='bx bx-check-circle', max_length=80, verbose_name='Classe icône Boxicons')),
                ('title', models.CharField(max_length=100, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Valeur ajoutée',
                'verbose_name_plural': 'Valeurs ajoutées',
                'ordering': ['order'],
            },
        ),
    ]
