# Generated by Django 6.0.6 on 2026-06-21 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cover_static',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Image statique (chemin dans /static/)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/covers/', verbose_name='Image principale'),
        ),
    ]
